M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Sun 27 Aug 2023 03:16:51 PM MDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-27T15:16:51-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X5.5808Y-3.4378
X5.5816Y-2.8658
X6.1781Y-3.44
X6.18Y-2.86
T0
M30
